export const cars = [
  {
    id: 1,
    vehicle: "Audi A4 2.0 TDI Quattro S-Line",
    brand: "Audi",
    model: "A4",
    year: 2022,
    price: 28500,
    originalPrice: 32000,
    kms: 15000,
    plate: "1234-ABC",
    days: 45,
    etiq: "ECO",
    status: "Disponibles",
    color: "Gris Nardo",
    fuel: "Diésel",
    transmission: "Automático",
    doors: 4,
    seats: 5,
    power: "190 CV",
    consumption: "4.8 L/100km",
    emissions: "126 g/km CO2",
    image: "https://cdn.autobild.es/sites/navi.axelspringer.es/public/bdc/dc/fotos/Audi-A4_Avant_2013_C01.jpg?tf=3840x",
    images: [
      "https://cdn.autobild.es/sites/navi.axelspringer.es/public/bdc/dc/fotos/Audi-A4_Avant_2013_C01.jpg?tf=3840x",
      "https://cdn.autobild.es/sites/navi.axelspringer.es/public/bdc/dc/fotos/Audi-A4_Avant_2013_C02.jpg?tf=3840x",
      "https://cdn.autobild.es/sites/navi.axelspringer.es/public/bdc/dc/fotos/Audi-A4_Avant_2013_C03.jpg?tf=3840x",
      "https://cdn.autobild.es/sites/navi.axelspringer.es/public/bdc/dc/fotos/Audi-A4_Avant_2013_C04.jpg?tf=3840x",
    ],
    description: "Audi A4 en excelente estado, con mantenimiento al día y todas las revisiones oficiales. Vehículo de un solo propietario, no fumador. Incluye libro de mantenimiento y segunda llave.",
    features: [
      "Sistema de navegación MMI",
      "Asientos de cuero",
      "Climatizador automático",
      "Sensores de aparcamiento",
      "Faros LED",
      "Llantas de aleación 18''",
      "Control de crucero adaptativo",
      "Asistente de cambio de carril",
    ],
    portals: ["AutoScout24", "Coches.net"],
    portalUrls: {
      AutoScout24: "https://autoscout24.com/anuncio-123",
      "Coches.net": "https://coches.net/anuncio-456",
    },
    location: "Madrid, España",
    dealer: {
      name: "AutoDeal Madrid",
      phone: "+34 91 123 45 67",
      email: "info@autodealmadrid.com",
      rating: 4.8,
      reviews: 127,
    },
    history: [
      { date: "2024-01-15", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2024-01-20", event: "Publicado en AutoScout24", type: "success" },
      { date: "2024-01-22", event: "Primera visita programada", type: "info" },
      { date: "2024-02-01", event: "Precio reducido a €28,500", type: "warning" },
    ],
    maintenance: [
      { date: "2023-12-15", service: "Revisión oficial 15.000 km", cost: 280 },
      { date: "2023-06-20", service: "Cambio de aceite y filtros", cost: 120 },
      { date: "2023-01-10", service: "ITV pasada", cost: 45 },
    ],
  },
  {
    id: 2,
    vehicle: "BMW X3 xDrive20d",
    brand: "BMW",
    model: "X3",
    year: 2023,
    price: 45000,
    originalPrice: 48000,
    kms: 8000,
    plate: "5678-DEF",
    days: 12,
    etiq: "C",
    status: "En preparación",
    color: "Negro Zafiro",
    fuel: "Diésel",
    transmission: "Automático",
    doors: 5,
    seats: 5,
    power: "190 CV",
    consumption: "5.4 L/100km",
    emissions: "142 g/km CO2",
    image: "https://www.km77.com/media/fotos/bmw_x3_2022_8015_1.jpg",
    images: [
      "https://www.km77.com/media/fotos/bmw_x3_2022_8015_1.jpg",
      "https://www.km77.com/media/fotos/bmw_x3_2022_8015_2.jpg",
      "https://www.km77.com/media/fotos/bmw_x3_2022_8015_3.jpg",
      "https://www.km77.com/media/fotos/bmw_x3_2022_8015_4.jpg",
    ],
    description: "BMW X3 en perfectas condiciones, con todos los servicios al día. SUV premium con tracción integral xDrive. Ideal para familias que buscan lujo y versatilidad.",
    features: [
      "Sistema iDrive 7.0",
      "Asientos de cuero Dakota",
      "Climatizador automático bi-zona",
      "Cámara de visión trasera",
      "Faros LED adaptativos",
      "Llantas de aleación 19''",
      "Asistente de aparcamiento",
      "Control de crucero activo",
    ],
    portals: ["AutoScout24", "Milanuncios"],
    portalUrls: {
      AutoScout24: "https://autoscout24.com/anuncio-bmw-456",
      Milanuncios: "https://milanuncios.com/anuncio-bmw-789",
    },
    location: "Barcelona, España",
    dealer: {
      name: "BMW Premium Barcelona",
      phone: "+34 93 456 78 90",
      email: "info@bmwpremium.com",
      rating: 4.7,
      reviews: 89,
    },
    history: [
      { date: "2024-02-10", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2024-02-15", event: "Inspección técnica completa", type: "success" },
      { date: "2024-02-18", event: "Publicado en portales", type: "info" },
    ],
    maintenance: [
      { date: "2024-01-20", service: "Revisión oficial 8.000 km", cost: 320 },
      { date: "2023-08-15", service: "Cambio de aceite y filtros", cost: 180 },
    ],
  },
  {
    id: 3,
    vehicle: "Ford Focus 1.5 EcoBoost",
    brand: "Ford",
    model: "Focus",
    year: 2021,
    price: 18900,
    originalPrice: 21000,
    kms: 32000,
    plate: "9012-GHI",
    days: 78,
    etiq: "B",
    status: "Reservados",
    color: "Azul Magnético",
    fuel: "Gasolina",
    transmission: "Manual",
    doors: 5,
    seats: 5,
    power: "150 CV",
    consumption: "5.7 L/100km",
    emissions: "129 g/km CO2",
    image: "https://img.pymecar.com/vehiculo/2/tn5_4497_240307143938_1.jpg",
    images: [
      "https://img.pymecar.com/vehiculo/2/tn5_4497_240307143938_1.jpg",
      "https://img.pymecar.com/vehiculo/2/tn5_4497_240307143938_2.jpg",
      "https://img.pymecar.com/vehiculo/2/tn5_4497_240307143938_3.jpg",
      "https://img.pymecar.com/vehiculo/2/tn5_4497_240307143938_4.jpg",
    ],
    description: "Ford Focus en buen estado general. Vehículo familiar perfecto para ciudad y carretera. Motor EcoBoost eficiente y fiable. Mantenimiento al día.",
    features: [
      "Sistema SYNC 3",
      "Asientos en tela premium",
      "Aire acondicionado manual",
      "Sensores de aparcamiento traseros",
      "Faros halógenos",
      "Llantas de aleación 16''",
      "Control de crucero",
      "Bluetooth y USB",
    ],
    portals: ["Coches.net"],
    portalUrls: {
      "Coches.net": "https://coches.net/anuncio-ford-123",
    },
    location: "Valencia, España",
    dealer: {
      name: "Ford Valencia",
      phone: "+34 96 123 45 67",
      email: "info@fordvalencia.com",
      rating: 4.5,
      reviews: 156,
    },
    history: [
      { date: "2023-11-20", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2023-12-01", event: "Primera visita", type: "info" },
      { date: "2024-01-15", event: "Precio reducido", type: "warning" },
      { date: "2024-02-20", event: "Reservado por cliente", type: "success" },
    ],
    maintenance: [
      { date: "2023-10-10", service: "Revisión 30.000 km", cost: 180 },
      { date: "2023-04-15", service: "Cambio de aceite", cost: 80 },
      { date: "2023-01-20", service: "ITV pasada", cost: 45 },
    ],
  },
  {
    id: 4,
    vehicle: "Tesla Model 3 Long Range",
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 52000,
    originalPrice: 55000,
    kms: 5000,
    plate: "3456-JKL",
    days: 8,
    etiq: "0",
    status: "Disponibles",
    color: "Blanco Perla",
    fuel: "Eléctrico",
    transmission: "Automático",
    doors: 4,
    seats: 5,
    power: "351 CV",
    consumption: "14.3 kWh/100km",
    emissions: "0 g/km CO2",
    image: "https://cdn.motor1.com/images/mgl/jzjBk/s1/tesla-model-3-awd-long-range-2021-prueba.webp",
    images: [
      "https://cdn.motor1.com/images/mgl/jzjBk/s1/tesla-model-3-awd-long-range-2021-prueba.webp",
      "https://octane.rent/wp-content/uploads/2024/11/Tesla-Model-3-white-1-600x400.webp",
      "https://hips.hearstapps.com/hmg-prod/images/2024-tesla-model-3-long-range-rwd-112-66feb72b5731d.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/2024-tesla-model-3-long-range-rwd-101-66feb72765eed.jpg?crop=1xw:1xh;center,top&resize=980:*",
    ],
    description: "Tesla Model 3 prácticamente nuevo. Vehículo eléctrico premium con la última tecnología de Tesla. Autonomía de 448 km WLTP. Carga rápida y conducción autónoma.",
    features: [
      "Autopilot con conducción autónoma",
      "Pantalla táctil de 15 pulgadas",
      "Techo de cristal panorámico",
      "Cargador móvil incluido",
      "Conectividad Premium",
      "Llantas de aleación 18''",
      "Sistema de audio premium",
      "Actualizaciones OTA",
    ],
    portals: ["AutoScout24", "Coches.net", "Milanuncios"],
    portalUrls: {
      AutoScout24: "https://autoscout24.com/anuncio-tesla-789",
      "Coches.net": "https://coches.net/anuncio-tesla-456",
      Milanuncios: "https://milanuncios.com/anuncio-tesla-123",
    },
    location: "Madrid, España",
    dealer: {
      name: "Tesla Madrid",
      phone: "+34 91 987 65 43",
      email: "info@teslamadrid.com",
      rating: 4.9,
      reviews: 234,
    },
    history: [
      { date: "2024-02-25", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2024-02-26", event: "Inspección técnica Tesla", type: "success" },
      { date: "2024-02-27", event: "Publicado en todos los portales", type: "info" },
    ],
    maintenance: [
      { date: "2024-01-15", service: "Revisión anual Tesla", cost: 150 },
      { date: "2023-06-20", service: "Actualización de software", cost: 0 },
    ],
  },
  {
    id: 5,
    vehicle: "Toyota Corolla Hybrid",
    brand: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 24500,
    originalPrice: 26500,
    kms: 18000,
    plate: "7890-MNO",
    days: 156,
    etiq: "ECO",
    status: "Vendidos",
    color: "Gris Platino",
    fuel: "Híbrido",
    transmission: "CVT",
    doors: 5,
    seats: 5,
    power: "122 CV",
    consumption: "3.9 L/100km",
    emissions: "89 g/km CO2",
    image: "https://scene7.toyota.eu/is/image/toyotaeurope/review-nuevo-corolla?wid=1280&fit=fit,1&ts=0&resMode=sharp2&op_usm=1.75,0.3,2,0",
    images: [
      "https://scene7.toyota.eu/is/image/toyotaeurope/review-nuevo-corolla?wid=1280&fit=fit,1&ts=0&resMode=sharp2&op_usm=1.75,0.3,2,0",
      "https://scene7.toyota.eu/is/image/toyotaeurope/corolla-interior-1?wid=1280&fit=fit,1&ts=0&resMode=sharp2&op_usm=1.75,0.3,2,0",
      "https://scene7.toyota.eu/is/image/toyotaeurope/corolla-rear-view?wid=1280&fit=fit,1&ts=0&resMode=sharp2&op_usm=1.75,0.3,2,0",
      "https://scene7.toyota.eu/is/image/toyotaeurope/corolla-profile?wid=1280&fit=fit,1&ts=0&resMode=sharp2&op_usm=1.75,0.3,2,0",
    ],
    description: "Toyota Corolla Hybrid vendido recientemente. Vehículo híbrido muy eficiente, perfecto para uso urbano y viajes largos. Consumo muy bajo y gran fiabilidad Toyota.",
    features: [
      "Sistema Toyota Safety Sense 2.0",
      "Asientos mixtos tela/cuero sintético",
      "Climatizador automático",
      "Sensores de aparcamiento",
      "Faros LED",
      "Llantas de aleación 16''",
      "Sistema multimedia Toyota Touch 2",
      "Cámara de marcha atrás",
    ],
    portals: ["Coches.net", "Milanuncios"],
    portalUrls: {
      "Coches.net": "https://coches.net/anuncio-toyota-vendido",
      Milanuncios: "https://milanuncios.com/anuncio-toyota-vendido",
    },
    location: "Sevilla, España",
    dealer: {
      name: "Toyota Sevilla",
      phone: "+34 95 456 78 90",
      email: "info@toyotasevilla.com",
      rating: 4.6,
      reviews: 198,
    },
    history: [
      { date: "2023-09-15", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2023-10-20", event: "Primera visita", type: "info" },
      { date: "2024-01-10", event: "Precio reducido", type: "warning" },
      { date: "2024-02-28", event: "Vendido", type: "success" },
    ],
    maintenance: [
      { date: "2024-01-20", service: "Revisión 15.000 km", cost: 120 },
      { date: "2023-07-15", service: "Cambio de aceite", cost: 60 },
      { date: "2023-02-10", service: "ITV pasada", cost: 45 },
    ],
  },
  {
    id: 6,
    vehicle: "Audi Q5 40 TDI",
    brand: "Audi",
    model: "Q5",
    year: 2021,
    price: 38000,
    originalPrice: 42000,
    kms: 25000,
    plate: "2468-PQR",
    days: 89,
    etiq: "C",
    status: "Disponibles",
    color: "Negro Mythos",
    fuel: "Diésel",
    transmission: "Automático",
    doors: 5,
    seats: 5,
    power: "204 CV",
    consumption: "5.8 L/100km",
    emissions: "153 g/km CO2",
    image: "/placeholder.svg?height=120&width=200",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description: "Audi Q5 en excelente estado. SUV premium con tracción quattro. Perfecto equilibrio entre lujo, rendimiento y practicidad. Ideal para familias exigentes.",
    features: [
      "Sistema MMI Navigation plus",
      "Asientos de cuero Valcona",
      "Climatizador automático tri-zona",
      "Cámara de visión trasera",
      "Faros Matrix LED",
      "Llantas de aleación 19''",
      "Asistente de aparcamiento plus",
      "Control de crucero adaptativo",
    ],
    portals: ["AutoScout24"],
    portalUrls: {
      AutoScout24: "https://autoscout24.com/anuncio-audi-q5",
    },
    location: "Bilbao, España",
    dealer: {
      name: "Audi Bilbao",
      phone: "+34 94 567 89 01",
      email: "info@audibilbao.com",
      rating: 4.7,
      reviews: 112,
    },
    history: [
      { date: "2023-11-01", event: "Vehículo añadido al inventario", type: "info" },
      { date: "2023-11-15", event: "Publicado en AutoScout24", type: "success" },
      { date: "2024-01-20", event: "Primera visita programada", type: "info" },
      { date: "2024-02-10", event: "Precio reducido a €38,000", type: "warning" },
    ],
    maintenance: [
      { date: "2023-09-20", service: "Revisión 25.000 km", cost: 280 },
      { date: "2023-03-15", service: "Cambio de aceite y filtros", cost: 150 },
      { date: "2022-12-10", service: "ITV pasada", cost: 45 },
    ],
  },
]