export const cars = [
  {
    id: 1,
    vehicle: "Audi A4 2.0 TDI",
    price: 28500,
    year: 2022,
    kms: 15000,
    plate: "1234-ABC",
    days: 45,
    etiq: "ECO",
    portals: ["AutoScout24", "Coches.net"],
    status: "Disponibles",
    image: "/placeholder.svg?height=120&width=200",
    brand: "Audi",
  },
  {
    id: 2,
    vehicle: "BMW X3 xDrive20d",
    price: 45000,
    year: 2023,
    kms: 8000,
    plate: "5678-DEF",
    days: 12,
    etiq: "C",
    portals: ["AutoScout24", "Milanuncios"],
    status: "En preparación",
    image: "/placeholder.svg?height=120&width=200",
    brand: "BMW",
  },
  {
    id: 3,
    vehicle: "Ford Focus 1.5 EcoBoost",
    price: 18900,
    year: 2021,
    kms: 32000,
    plate: "9012-GHI",
    days: 78,
    etiq: "B",
    portals: ["Coches.net"],
    status: "Reservados",
    image: "/placeholder.svg?height=120&width=200",
    brand: "Ford",
  },
  {
    id: 4,
    vehicle: "Tesla Model 3 Long Range",
    price: 52000,
    year: 2023,
    kms: 5000,
    plate: "3456-JKL",
    days: 8,
    etiq: "0",
    portals: ["AutoScout24", "Coches.net", "Milanuncios"],
    status: "Disponibles",
    image: "/placeholder.svg?height=120&width=200",
    brand: "Tesla",
  },
  {
    id: 5,
    vehicle: "Toyota Corolla Hybrid",
    price: 24500,
    year: 2022,
    kms: 18000,
    plate: "7890-MNO",
    days: 156,
    etiq: "ECO",
    portals: ["Coches.net", "Milanuncios"],
    status: "Vendidos",
    image: "/placeholder.svg?height=120&width=200",
    brand: "Toyota",
  },
  {
    id: 6,
    vehicle: "Audi Q5 40 TDI",
    price: 38000,
    year: 2021,
    kms: 25000,
    plate: "2468-PQR",
    days: 89,
    etiq: "C",
    portals: ["AutoScout24"],
    status: "Disponibles",
    image: "/placeholder.svg?height=120&width=200",
    brand: "Audi",
  },
]